-- 코드를 작성해주세요
-- COUNT(*) : NULL 포함해서 셈 / COUNT(칼럼명) : NULL 빼고 셈
SELECT P.ID, COUNT(C.ID) AS CHILD_COUNT
FROM ECOLI_DATA AS P
LEFT JOIN ECOLI_DATA AS C
ON P.ID = C.PARENT_ID
GROUP BY P.ID
ORDER BY P.ID ASC;