-- TIMEDIFF(나중날짜, 먼저날짜) : 시간(HH:MM:SS) 형태로 차이를 반환
SELECT I.ANIMAL_ID, I.NAME -- , TIMEDIFF(O.DATETIME, I.DATETIME)
FROM ANIMAL_INS I JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE O.ANIMAL_ID IS NOT NULL
-- ORDER BY TIMEDIFF(O.DATETIME, I.DATETIME) DESC
ORDER BY (O.DATETIME - I.DATETIME) DESC
LIMIT 2
;