-- ID 당 여러 개의 보유 스킬이 붙어 여러 ID가 뜨기 때문에 DISTINCT를 꼭 써줘야 한다.
SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
-- & : 비트 연산
FROM SKILLCODES S JOIN DEVELOPERS D ON S.CODE = S.CODE & D.SKILL_CODE
WHERE S.CATEGORY = 'Front End'
ORDER BY D.ID;