SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM SKILLCODES S JOIN DEVELOPERS D ON S.CODE = S.CODE & D.SKILL_CODE
WHERE S.NAME IN ('Python', 'C#')
ORDER BY 1
;

/*
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
WHERE SKILL_CODE & (
                    SELECT SUM(CODE)
                    FROM SKILLCODES
                    WHERE NAME IN ('Python', 'C#'))
ORDER BY ID
*/
