-- 두번째 방법 - LEFT(문자열, 왼쪽부터 자를 길이)
SELECT LEFT(PRODUCT_CODE, 2) AS CATEGORY, COUNT(*) AS PRODUCTS
FROM PRODUCT
-- 첫번째 방법
-- SELECT CATEGORY, COUNT(CATEGORY) AS PRODUCTS
-- FROM (SELECT LEFT(PRODUCT_CODE, 2) AS CATEGORY FROM PRODUCT) AS C
GROUP BY CATEGORY
ORDER BY CATEGORY
;