SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO JOIN FISH_NAME_INFO USING(FISH_TYPE)
-- IN 조건의 (FISH_TYPE, LENGTH)는 서브쿼리에서 반환된 (FISH_TYPE, MAX(LENGTH)) 값들과 정확히 일치하는 경우만 필터링한다.
WHERE (FISH_TYPE, LENGTH) IN (SELECT FISH_TYPE, MAX(LENGTH) FROM FISH_INFO GROUP BY 1)
ORDER BY 1;